src/data-service/device-service.ts
src/device-managers/AndroidDeviceManager.ts
src/device-managers/IOSDeviceManager.ts
src/device-managers/index.ts
src/interfaces/IDeviceManager.ts
src/plugin.ts
test/unit/AndroidDeviceManager.spec.js
test/unit/IOSDeviceManager.spec.js

Fix for getting device details only for new devices during polling

---

package.json

copy public directory to lib folder in prepublish script

---

README.md
package-lock.json
package.json
src/plugin.ts

User can now define specific device udid's as part of capability object

---

package-lock.json
package.json
src/CapabilityManager.ts

Include a check before adding mjpegServerPort capability

---

src/device-utils.ts

trim whitespaces from udids capability

---

src/commands/index.ts
test/unit/commands.spec.js

Along with the fix, I have also added the unit tests to cover the same.
fix #513

fix handle command not registered to plugin class

---

package-lock.json
package.json
src/app.ts
src/data-service/db.ts
src/data-service/pluginArgs.ts
src/device-utils.ts
src/plugin.ts

http://localhost:4723/device-farm/api/cliArgs

Expose cli args to client

---

README.md
azure-pipelines.yml
package-lock.json
package.json
src/chromeUtils.ts
src/helpers.ts
test/e2e/android/cloud/conf.spec.js

instead of cloud specific user name and password environment variables, use CLOUD_USER and CLOUD_KEY. Also removed the hardcoded url for BrowserStack

Use CLOUD_USER and CLOUD_KEY consistently for all cloud executions

---

package-lock.json
package.json

Installing go-ios is failing as unzipper dependency is missing. This PR fixes the issue.

Add unzipper dependencies

---

README.md
package-lock.json
package.json

Fix simulator contract

---

src/plugin.ts

@saikrishna321 @SrinivasanTarget - please review

add error logs when failed to create a session

---

package-lock.json
package.json
src/plugin.ts

updated version to 8.3.1
@saikrishna321  @SrinivasanTarget

Error logs

---

package-lock.json
package.json
src/data-service/device-service.ts
src/device-utils.ts
src/plugin.ts

@saikrishna321  @SrinivasanTarget

added more logs. bumped version to 8.3.3

---

package-lock.json
package.json
src/data-service/device-service.ts
src/plugin.ts

@saikrishna321 @SrinivasanTarget

added JSON.srtingify and bumped version to v8.3.4

---

package-lock.json
package.json
src/plugin.ts
src/wd-command-proxy.ts

bumped version to 8.3.11
@saikrishna321 
@SrinivasanTarget

Add proxy, if available, to createProxyMiddleware (addProxyHandler)

---

package-lock.json
package.json
src/commands/handle.ts
src/wd-command-proxy.ts

@saikrishna321 
@SrinivasanTarget

Change proxy order

---

package-lock.json
package.json
src/device-utils.ts

@saikrishna321 
@SrinivasanTarget

remove the isMac check for deviceType and bumped version 8.3.14

---

src/device-managers/IOSDeviceManager.ts
src/device-utils.ts
src/plugin.ts

Remove stable devices from hub when node is down

---

package-lock.json
package.json
src/device-managers/AndroidDeviceManager.ts
src/device-managers/IOSDeviceManager.ts
src/device-managers/index.ts
src/device-utils.ts
test/unit/AndroidDeviceManager.spec.ts

attach nodeId for tracked devices

---

package-lock.json
package.json
src/data-service/device-service.ts
src/debugLog.ts
src/device-utils.ts
src/plugin.ts

Start the appium server with process.env.DEVICE_FARM_DEBUG=true

Print more debug logs better debugging

---

package-lock.json
package.json
src/data-service/device-service.ts
src/plugin.ts

Configure axios to keep session alive

---

package-lock.json
package.json
src/CapabilityManager.ts
src/plugin.ts

Fix capability checks for skipReport

---

package-lock.json
package.json
src/CapabilityManager.ts

Fix session creation when wda is not uploaded

---

.gitignore
src/proxy/wd-command-proxy.ts

Gracefully handle unexpected errors in dashboard module

---

package-lock.json
package.json
src/device-managers/cloud/CapabilityManager.ts

Check for null capability for cloud execution

---

src/CapabilityManager.ts

Fix ios manual control

---

src/CapabilityManager.ts

fix: add wdalocalport when running parallel sessions

---

package-lock.json
package.json
src/device-managers/IOSDeviceManager.ts
src/device-utils.ts
src/plugin.ts

fix: add support to flutter integration driver

---

src/device-managers/IOSDeviceType.ts

feat: add support for keyboard interaction

---

README.md

Hi @saikrishna321, sorry for the wait. Here's my testimonial for Appium Device farm!

Add testimonial in README.md

---

package-lock.json
src/CapabilityManager.ts
src/device-managers/IOSDeviceManager.ts
src/device-utils.ts
src/plugin.ts
src/proxy/wd-command-proxy.ts
test/integration/androidDevices.spec.ts
test/integration/ios/01iOSSimulator.spec.ts
test/integration/ios/02iOSDevices.spec.ts
test/unit/device-utils.spec.ts

fix: improve device allocation and session creation logic

---

package-lock.json
src/CapabilityManager.ts

fix: ios port and android streaming issue

---

src/plugin.ts

fix: Unable to take ios devices from node for manual interaction

---

src/device-managers/IOSDeviceType.ts

Added screen sizes for iPhone 16

fix: Update IOSDeviceType.ts

---

package-lock.json
src/device-managers/IOSDeviceType.ts

 fix: update screen size for iPad Pro 13-inch

---

package-lock.json
src/data-service/device-service.ts

feat: #1459 add support to edit device name in the dashboard

---

package-lock.json
src/config.ts
src/plugin.ts
src/types/Config.ts

https://github.com/user-attachments/assets/3a0ad92f-ddae-4e4f-ac77-2724f9fdbf9e

fix: make debugging simple by serving appium logs in the dashboard

---

src/device-utils.ts

BREAKING CHANGE: Following changes are added
- Added authentication module with user and team management
- Enhanced automation runs with access key authentication
- Improved device and server management capabilities
- Database schema changes that may result in loss of existing data
Fixes: #1635 #1613 #1588 #1575 #1523 #1411 #1333 #1230 #1171

feat: use newCommandTimeoutSec for manual device control

---

package-lock.json
package.json

fix: remove node-pty dependency

---

package-lock.json

This pull request updates the `src/modules` submodule to a newer commit. No other changes are included.
#1810 
#1771

fix: remote hub for ios and apple tv for manual interaction

---

src/utils/auth.ts

fix: issues with live streaming and build logs
