README.md, package.json, remote-config.json, src/device-managers/AndroidDeviceManager.ts, src/device-managers/IOSDeviceManager.ts, src/device-managers/index.ts, src/interfaces/IDeviceManager.ts, src/plugin.ts, test/integration/androidDevices.spec.js, test/integration/iOSDevices.spec.js, test/integration/iOSSimulator.spec.js, test/unit/AndroidDeviceManager.spec.js, test/unit/IOSDeviceManager.spec.js, test/unit/RemoteIOs.spec.js
Closes #455 
Closes #516 
This changes CLI argument `include-simulators` to `--plugin-device-farm-device-types=both(default)|simulated|real`, allowing someone to specify which types of devices they want to appear in the device farm
=> Change CLI argument `include-simulators` to `device-types`

src/data-service/device-service.ts, src/device-utils.ts, src/interfaces/IDevice.ts
Closes #529 
These changes honor 'appium:newCommandTimeout' capability otherwise defaults to 60 seconds to match Appium before releasing device due to inactivity
=> Respect 'appium:newCommandTimeout' capability when releasing inactive devices

package-lock.json, package.json, src/CapabilityManager.ts, src/device-managers/IOSDeviceManager.ts, src/device-utils.ts, src/interfaces/IDevice.ts, test/unit/IOSDeviceManager.spec.js, test/unit/RemoteIOs.spec.js
I've been noticing that the parallelization of sessions is pretty slow for the real iOS devices I'm testing on. Appium recommends setting unique values for `udid`, `wdaLocalPort`, `derivedDataPath`, `mjpegServerPort`
https://github.com/appium/appium-xcuitest-driver#important-real-device-capabilities
I noticed a couple of issues, before the changes in this branch:
1. The `mjpegServerPort` is incorrect on subsequent runs. If you use the port from the first session, you can view the video. The change in this branch sets it once for each device and leaves it as-is (similar to the `wdaLocalPort`)
2. The `derivedDataPath` is not getting set so the WebDriverAgent seems to be getting built more than it needs to. Setting it as a unique path for each device makes parallel execution faster
=> Set unique derivedDataPath and mjpegServerPort for each iOS device

README.md, package-lock.json, package.json, src/data-service/device-service.ts, src/device-utils.ts, src/interfaces/IDeviceFilterOptions.ts, test/unit/device-service.spec.js, test/unit/plugin.spec.js
I'd like to be able to target devices with a specific sdk (`appium:platformVersion`).
I tried to use `appium:minSDK` while adding `appium:maxSDK` however found this to not work when device sdk couldn't be casted to a number (e.g. `16.1.1`).
So the easiest  way to support my workflow was to consider `platformVersion` when filtering devices by capability
=> Support platformVersion capability when filtering devices

package-lock.json, package.json, src/device-utils.ts
I missed this in the first tvOS PR https://github.com/AppiumTestDistribution/appium-device-farm/pull/603
Both iOS and tvOS device platforms should use the iOSCapabilities as they both use the XCUITest driver
=> Fix tvOS capabilities

src/device-utils.ts
Added a temp fix that will unblock folks.
Issue #619 needs further investigation 
1. Why is data being stored in the cache file (advantages) ?
2. Are we going to hold device utilization times even after the server restart?
3. Scenario for file corruption 
etc.
=> Temp fix to handle cache file corruption.

README.md, package-lock.json, package.json, src/data-service/device-service.ts, src/device-utils.ts, src/interfaces/IDeviceFilterOptions.ts, test/unit/device-service.spec.js, test/unit/plugin.spec.js
This adds an `appium:maxSDK` capability. Combined with `appium:minSDK` you will be able to filter devices to a given range. 
Also, when working on https://github.com/AppiumTestDistribution/appium-device-farm/pull/576, I noticed that the `minSDK` filter only worked if the `device.sdk` could be cast to a float. For devices with semantic versioning, such as `16.1.2`, this filter didn't work. Using `semver`, you can now filter devices that have semantic versioning.
=> Add maxSDK capability + semantic version filtering

package-lock.json, package.json, src/data-service/device-service.ts
Follow-up PR to https://github.com/AppiumTestDistribution/appium-device-farm/pull/675 which fixes a bug in the `getDevice()` query and bumps version
=> Fix bug in getDevice() query and bump version

package-lock.json, package.json, src/device-managers/AndroidDeviceManager.ts, test/unit/AndroidDeviceManager.spec.js
`appium-device-farm` plugin will crash when device status is `unathorized`.
This PR prevents calling `deviceInfo` when device state is `unauthorized`.
It would be nice to have these `unauthorized` device to show up in the UI so someone can take an action. Maybe in another PR.
=> Avoid crash when device is in unauthorized state.

src/device-managers/cloud/CapabilityManager.ts
All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: pCloudy_ApiKey,pCloudy_Username
[HTTP] --> POST /session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:adbExecTimeout":140000,"appium:appActivity":"com.games24x7.coregame.common.deeplink.DeepLinkActivity","appium:appPackage":"com.my11circle.android.stage","appium:autoGrantPermissions":true,"appium:automationName":"UiAutomator2","appium:deviceName":"android","appium:noReset":false,"appium:noSign":true,"appium:uiautomator2ServerInstallTimeout":120000,"platformName":"ANDROID","appium:clearDeviceLogsOnStart":true,"appium:nativeWebScreenshot":true,"appium:mjpegServerPort":52672,"appium:pCloudy_DeviceVersion":"8.0.0","appium:pCloudy_DeviceManufacturer":"demo","appium:udid":" …
=> Fix : pCloudy vendor prefix

src/device-managers/AndroidDeviceManager.ts, test/unit/AndroidDeviceManager.spec.js, test/unit/device-service.spec.js
In my device-farm, the hub/nodes sometimes crash with the following log:
```
[ADB] Running '/Users/ci/Library/Android SDK/platform-tools/adb -P 5037 -s abcdef shell getprop init.svc.bootanim'
uncaughtException: Timed out after waiting for 60000 ms
Error: Timed out after waiting for 60000 ms
at /Users/ci/.appium/node_modules/appium-device-farm/node_modules/async-wait-until/dist/index.js:1:1034
at runNextTicks (node:internal/process/task_queues:60:5)
at listOnTimeout (node:internal/timers:540:9)
at processTimers (node:internal/timers:514:7)
uncaughtException: Timed out after waiting for 60000 ms
```
This PR adds typing for `getDeviceProperty` and adds graceful handling for other methods when `getDeviceProperty` returns `undefined`.
=> fix: gracefully handle adb timeout

LICENSE, PROPRIETARY-LICENSE.txt, README.md
BREAKING CHANGE:
This PR introduces a dual licensing model for the Appium Device Farm Plugin to clarify the usage terms for both open source and proprietary components:
- Updates LICENSE file to reflect MIT license for open source components
- Adds PROPRIETARY-LICENSE.txt for obfuscated, proprietary modules
- Updates README with clear explanation of licensing structure
- Ensures compliance with open source principles while protecting proprietary code
This change aims to provide transparency to users about component licensing while maintaining the project's integrity and protecting proprietary elements.
=> BREAKING CHANGE: Implement Dual Licensing Open Source MIT and Proprietary for Specific Components

package-lock.json
=> fix: enable livestream for android based on capability

documentation/docs/ios-signing.md, src/scripts/ios-sign.ts
Hello,
I am a user of the `appium-device-farm` plugin and have been enjoying its capabilities.
After updating to Xcode 16 and using this plugin, I encountered an issue where building the `wda-resign.ipa` did not work correctly with newly added iOS real devices. Upon investigation, I found that starting from Xcode 16, the directory path where provisioning profiles are stored has changed. I resolved the issue by explicitly specifying the correct directory path during the WDA build process.
Since this project uses the `ios-mobileprovision-finder` library, I looked into its repository and noticed that a related PR addressing this issue was submitted 3 weeks ago. However, as it is unclear when the PR will be merged and a new version released, I decided to implement a temporary fix myself. …
=> fix: provisioning profile file path after Xcode 16

src/device-managers/IOSDeviceManager.ts
=> fix: added missing nodeId for ios simulators when registered from node

src/device-managers/IOSDeviceType.ts
Update the Width and Height for iPad Mini 7
=> fix: update Width and Height for iPad Mini 7

src/device-utils.ts
- Remove query params from app path ( everything after “?” )
- Lower‑case and normalize the path for URLs and local file paths
=> fix: strip query params in getDeviceTypeFromApp

README.md, documentation/docs/index.md, documentation/docs/ios-signing.md, documentation/docs/setup.md, documentation/docs/troubleshooting.md
- Update iOS signing documentation to include tvOS support
- Add dedicated tvOS WDA preparation section with step-by-step instructions
- Update setup.md with tvOS device management instructions
- Enhance overview documentation to mention tvOS devices
- Add tvOS troubleshooting section
- Update README.md with complete tvOS setup guide
- Include tvOS capabilities examples and prerequisites
- Document automatic platform detection for iOS vs tvOS WDA files
This update provides comprehensive documentation for users wanting to test on Apple TV devices using the Appium Device Farm plugin.
=> docs: Add comprehensive tvOS support documentation

src/CapabilityManager.ts
If we add the skipReport:True capability, then the app capability was not included in the final capabilities because there was a condition for exiting the findAppPath function.
`if (mergedCaps['df:skipReport']) return;`
all code
[issues-1760](https://github.com/AppiumTestDistribution/appium-device-farm/issues/1760)
=> chore: removed the return condition from the function in findAppPath

package-lock.json
This pull request updates the submodule reference for `dashboard-frontend` to point to a newer commit. No other changes are included.
Address #1795 
([dashboard-frontendL1-R1](diffhunk://#diff-1b4f3ae726fa110eb6200ecd7b6650899d0b42a7ac49d81589701304e16eef43L1-R1))
=> fix: show block and unblock in the dashboard for admin users only
